### ISSUE TITLE
git finish throws TypeError

### ISSUE THREAD

**Issue by rafpaf** [mako-taco/pivotal-git#17]
Traceback:
```
TypeError: Cannot read property 'stack' of null
    at /usr/local/lib/node_modules/pivotal-git/lib/internal/git.js:164:26
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by mako-taco** [comment]
I no longer plan on maintaining this project.  You should fork the repo or submit a PR
